- name: Create database in docker
  become: yes
  shell: "{{ item }}"
  with_items:
    - curl -X PUT http://wenyi:cloud@localhost:5984/all_data
    - curl -X PUT http://wenyi:cloud@localhost:5984/_replicator


- name: Set up replication
  become: yes
  command: "{{ item }}"
  with_items:
    - curl -X POST http://wenyi:cloud@localhost:5984/_replicator -d '{"source":"http://wenyi:cloud@localhost:5984/all_data", "target":"http://wenyi:cloud@{{replica}}:5984/all_data", "continuous":true}' -H "Content-Type:application/json"
