- name: download docker-compose
  shell: "{{item}}"
  with_items:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


- name: modify authentication
  shell: "{{item}}"
  with_items:
    - sudo chmod +x /usr/local/bin/docker-compose


- name: clone harvester git repo
  git:
    repo: https://github.com/PeggyZWY/visualisation-of-immigrant-Australian-population.git
    dest: /home/ubuntu/visualisation-github


- name: launch website
  shell: "{{item}}"
  args:
    chdir: /home/ubuntu/visualisation-github/website
  with_items:
    - sudo nohup docker-compose up
