version: "3.3"

services:
  api:
    stdin_open: true
    tty: true
    build: .
    image: nginx-gunicorn-flask:latest
    volumes:
      - ./app:/deploy/app
      - ./nginx_flask.conf:/etc/nginx/sites-available/nginx_flask.conf
      - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    command: '/usr/bin/supervisord'
